name: flutter_google_books
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_theme: ^6.4.0
  freezed: ^2.4.6
  http: ^1.2.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  flutter_hooks: ^0.20.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  another_flushbar: ^1.12.30
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  shared_preferences: ^2.2.2
  auto_route: ^7.8.4
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/appainter_theme.json
    - assets/images/